network: "./chain.yaml"
### initial-state: "./genesis.ssz"

eth1-deposit-contract-address: "0x9eED6A5741e3D071d70817beD551D0078e9a2706"
eth1-enabled: true
eth1-endpoint: "http://127.0.0.1:9779"

logging: "INFO"
log-color-enabled: true
log-include-events-enabled: true

p2p-port: 30000
p2p-advertised-port: 30000
p2p-enabled: true
p2p-discovery-enabled: true
p2p-snappy-enabled: true
p2p-discovery-bootnodes:
  - "enr:-KG4QO6QrRlWQ2Z5ss4XoUsrPvsepRuuogcHyC81gMQr7PJ3IFh41bDnGSl9iN_ijg2EgQeEQDpRPkE4FzD2ecbp6XoChGV0aDKQgGboQQAAARP__________4JpZIJ2NIJpcIQAAAAAiXNlY3AyNTZrMaEDpsGvSN7oM2c04ZT9mrG32TVj-sMhb6HiKc6LMEXYEyiDdGNwgnUwg3VkcIJ1MA"

rest-api-port: 5051
rest-api-enabled: True
rest-api-interface: "127.0.0.1"

validators-key-files:
  - "/home/user/.local/share/teku/keystore/validator_92db817/validator_92db817.json"
  - "/home/user/.local/share/teku/keystore/validator_97e54f5/validator_97e54f5.json"

validators-key-password-files:
  - "/home/user/.opt/goerli/witti/password.txt"
  - "/home/user/.opt/goerli/witti/password.txt"
