network: "./chain.yaml"
### initial-state: "./genesis.ssz"

eth1-deposit-contract-address: "0x42cc0FcEB02015F145105Cf6f19F90e9BEa76558"
eth1-enabled: true
eth1-endpoint: "http://127.0.0.1:8545"

logging: "INFO"
log-color-enabled: true
log-include-events-enabled: true

p2p-port: 30000
p2p-advertised-port: 30000
p2p-enabled: true
p2p-discovery-enabled: true
p2p-snappy-enabled: true
p2p-discovery-bootnodes:
  - "enr:-Ku4QMucba73OPBz2mgyYduH1tM50mZjaiLNEXMrEmTSnrgyEWMEF0zFK0QT6URu_wFfqW04gYn1wze-VQe-jb0L8r8Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhFzAVJaJc2VjcDI1NmsxoQIX4kyr2PR-bGTptaN9DbXa2A2L_rVfuIpMj7sCjPBov4N1ZHCCW8w"
  - "enr:-Ku4QJsxkOibTc9FXfBWYmcdMAGwH4bnOOFb4BlTHfMdx_f0WN-u4IUqZcQVP9iuEyoxipFs7-Qd_rH_0HfyOQitc7IBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhLAJM9iJc2VjcDI1NmsxoQL2RyM26TKZzqnUsyycHQB4jnyg6Wi79rwLXtaZXty06YN1ZHCCW8w"
  - "enr:-Ku4QF5CI2Ndig0cxR0fQjRolG1k6TggK0BV4Z5neog4U9LDYsTHz6Vv6qVyJ7b9L2r6S2Gu4Ek4Z7i7j-jAJBxHbmYBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhFe0zw-Jc2VjcDI1NmsxoQPD9aDKsFoUfpEMPuTgZ13qNsJZ31zMMrl3PsQXeX2cwYN1ZHCCW8w"
  - "enr:-Ku4QLE_fTEjP6K3OII1RYRLUMUbwV9dAh7-2vr7gkZnRXLxSy2B6C-b0nVVQcFYsUvp2Tgli7GKHBYpWiknTse7rrUBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhFzAVJaJc2VjcDI1NmsxoQKxhcZJCugFnVuRMMzE4JJe0E0FS71ctmAnx1Y2wCJwKoN1ZHCCpgQ"

rest-api-port: 5051
rest-api-enabled: True
rest-api-interface: "127.0.0.1"

validators-key-files:
  - "/home/user/.local/share/teku/witti/keystore/validator_ad5c50d/validator_ad5c50d.json"
  - "/home/user/.local/share/teku/witti/keystore/validator_b92fe9b/validator_b92fe9b.json"

validators-key-password-files:
  - "/home/user/.opt/goerli/witti/password.txt"
  - "/home/user/.opt/goerli/witti/password.txt"
