# network
network = "./chain-spec.yaml"

# p2p
p2p-enabled = true
p2p-port = 9000
p2p-discovery-enabled = true
p2p-advertised-port = 9000
p2p-static-peers = "/ip4/51.158.190.99/tcp/9000/p2p/16Uiu2HAm3XrDjg9GdaErVnof3RDqTFX84RAzonWgrkpXfC5Lgud8,/ip4/51.158.190.99/tcp/9500/p2p/16Uiu2HAmJ1LHCDcLvt9wWHfzxAhrrsBwzF9HHfe4ybiRH3XhwHit"
p2p-discovery-bootnodes = "enr:-Iu4QNBcP9u6jPQzkwRPHLwjxtMuPrSLZVgh-BbYGj-CZNyyJAtbNFoDVX9K5A282_xNCofc9E7vb2s6OgNGbdmxCIYBgmlkgnY0gmlwhDOevmOJc2VjcDI1NmsxoQJ4co8ifM7GT9mbDJmep_r98ZScURrrFChIJWciD6O6B4N0Y3CCIyiDdWRwgiMo,enr:-Iu4QKL0ZU_C2KFxcQ8XL-oNEXvK1hhH_No1a38Qcj60ShAPICg1mDJA5rlkKIinIWSuN5I1-0Yjab8_3qicJlUaJWwBgmlkgnY0gmlwhDOevmOJc2VjcDI1NmsxoQNPgJXFPxpEgf_IJhg1H8pAjwag7uc6JKwyyDc0OVHh7YN0Y3CCJRyDdWRwgiUc"

# interop
Xinterop-genesis-time = 1584316800
Xinterop-start-state = "./genesis.ssz"
Xinterop-enabled = true

# deposit
eth1-deposit-contract-address = "0xaA888248144Bc5d584a7f400839d0D912F21C39A"
eth1-endpoint = "http://127.0.0.1:8545"

# logging
logging = "INFO"
log-colour-enabled = true
log-include-events-enabled = true

# beacon rest api
rest-api-port = 5051
rest-api-enabled = true
rest-api-interface = "127.0.0.1"
